### ISSUE TITLE
Suggestion to make the first letter uppercase without JavaScript

### ISSUE THREAD

**Issue by smakosh** [whoisryosuke/gatsby-documentation-starter#4]
Simply use the `:first-letter` to achieve it, like so:

```css
.link:first-letter {
  text-transform: uppercase;
}
```

You could also achieve with the `capitalize` value like so:

```css
.link {
  text-transform: capitalize;
}
```
